[ Product Filter ] - FRONT
PrestaShopCorp/psxmarketingwithgoogle pull request #1724
Opened 2024-04-10 08:48 UTC by ClaraLpresta

2024-04-23 08:58 UTC, kktos requested changes

2024-04-24 07:09 UTC, ClaraLpresta commented on _dev/apps/ui/src/enums/product-feed/product-filter-condition.ts
> +  IS_NOT = 'isNot'
A voir avec Scott ou Sophie 😊

2024-04-24 07:12 UTC, ClaraLpresta commented on _dev/apps/ui/src/components/product-feed/settings/product-selection/type.ts
> +export type ProductFilterValue = number|string|boolean|null;
`value` peut être null si l'utilisateur n'a pas rempli le champ en question : https://www.figma.com/file/m1NpWYCFJGasLTh3uKaClR/%5BPS-Marketing%5D-Product-Filter?type=design&node-id=520-30040&mode=design&t=iBBjLUIwsqsYyWms-4

2024-04-24 07:14 UTC, ClaraLpresta commented on _dev/apps/ui/src/components/product-feed/settings/product-selection/product-selection.vue
> +  return '10000000-1000-4000-8000-100000000000'.replace(/[018]/g, (c) => (+c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> +c / 4).toString(16),
Pourquoi utiliser un package si on doit l'utiliser à un seul endroit ? Pour des questions de performance, est-ce que c'est pas mieux d'éviter les packages ?

2024-04-24 07:40 UTC, kktos requested changes

2024-04-24 07:40 UTC, kktos commented on _dev/apps/ui/src/components/product-feed/settings/product-selection/type.ts
> +export type ProductFilterValue = number|string|boolean|null;
oui, mais non.
le champ value est déjà facultatif. pas besoin d'ajouter null. C'est soit l'un, soit l'autre, mais pas les 2.
```typescript
export type ProductFilter = {
  id?: string,
  attribute?: number | string,
  condition?: string,
  conditionType?: string,
  value?: ProductFilterValue,
  values?: string[],
  errors?: ProductFilterErrors
}
```

2024-04-24 08:10 UTC, kktos requested changes

2024-04-24 08:10 UTC, kktos commented on _dev/apps/ui/src/components/product-feed/settings/product-selection/line-filter.vue
> +    updateAttribute(attribute: Attribute, isDefault: boolean) {
maybe change to updateField(attr; Attribute, type: Enum(Attr, Feature) )

2024-04-24 08:10 UTC, kktos commented on _dev/apps/ui/src/components/product-feed/settings/product-selection/type.ts
> +export interface Features {
is it used ? or are we using only the Attribute type as it is the very same.

2024-04-24 08:34 UTC, kktos requested changes

2024-04-24 08:34 UTC, kktos commented on _dev/apps/ui/src/components/campaign-creation/campaign-creation.vue
> +      return this.$options.filters?.formatPrice(0, this.currency).replace(/[\s.,0]*/g, '');
return type is string | undefined

2024-04-24 08:34 UTC, kktos commented on _dev/apps/ui/src/components/product-feed/settings/product-selection/line-filter.vue
> +            :prepend="attributeSelected.value === typeAttributes.PRICE && currencySymbol === 'en-gb' ? currencySymbol : undefined"
remove useless code
```
attributeSelected.value === typeAttributes.PRICE
```

2024-04-26 07:25 UTC, kktos requested changes

2024-04-26 07:25 UTC, kktos commented on _dev/apps/ui/src/components/product-feed/settings/product-selection/product-selection.vue
> +  id: uuidv4(),
there is no need for the function uuidv4().
a simple VV will do.
```typescript
const newFilter = () => ({
  id: crypto.randomUUID(),
});
```

2024-04-26 07:39 UTC, kktos requested changes

2024-04-26 07:39 UTC, kktos commented on _dev/apps/ui/src/components/product-feed/settings/product-selection/type.ts
> +
string type is too large for attribute. and no need to repeat the props for ProductFilterToSend 
```typescript
export type ProductFilter = {
  id: string,
  attribute: "price" | "brand" | "category" | "productId" | "outOfStock",
  condition?: string,
  conditionType?: string,
  value?: ProductFilterValue,
  values?: string[],
  errors?: ProductFilterErrors
}

export type ProductFilterToSend = Pick<ProductFilter, "attribute" | "condition" | "value" | "values">;
```

2024-04-26 07:53 UTC, ga-devfront commented on _dev/apps/ui/src/components/product-feed/settings/product-selection/type.ts
> +export type ProductFilterValue = number|string|boolean|null;
Sauf que `ProductFilterValue` n'est pas utiliser que dans le type `ProductFilter` mais à droites endroits dans le Vue ...

2024-04-26 08:20 UTC, kktos commented on _dev/apps/ui/src/components/product-feed/settings/product-selection/type.ts
> +export type ProductFilterValue = number|string|boolean|null;
yep. donc il faut les revoir aussi.
on a du javascript ici, pas du typescript. :/

2024-05-15 15:44 UTC, kseghair approved these changes

2024-05-16 06:23 UTC, merged