EMKTG-3153 : Pre monetization messages of module
PrestaShopCorp/psxmarketingwithgoogle pull request #1775
Opened 2024-07-04 09:14 UTC by ClaraLpresta

2024-07-05 08:42 UTC, ga-devfront requested changes

2024-07-05 08:42 UTC, ga-devfront commented on _dev/apps/ui/src/components/monetization/pre-monetization-banner-info.vue
> +      this.$store.dispatch('app/GET_BANNER_INFO_LOCAL_STORAGE_MONETIZATION', 0);
I think it's a better to use your enum her. Like this, your code is more maintainable.
```js
this.$store.dispatch(`app/${ActionsTypes.GET_BANNER_INFO_LOCAL_STORAGE_MONETIZATION}`, 0);
```

2024-07-05 08:42 UTC, ga-devfront commented on _dev/apps/ui/src/store/modules/app/actions.ts
> +  async [ActionsTypes.GET_BANNER_SUCCESS_LOCAL_STORAGE_MONETIZATION]({commit}: Context, value) {
for me it's not a GET but a SET.
And I think you can update the local storage her and not inside vue scripts. That's avoid duplication code.

2024-07-05 08:42 UTC, ga-devfront commented on _dev/apps/ui/src/store/modules/app/actions.ts
> +  async [ActionsTypes.GET_BANNER_INFO_LOCAL_STORAGE_MONETIZATION]({commit}: Context, value) {
same comment her

2024-07-05 08:42 UTC, ga-devfront commented on _dev/apps/ui/src/views/configuration-page.vue
> +    if (this.$refs.PreMonetizationPopin.$refs.modal) {
why do you don't use your store or local storage her ? And I think you can only use internal .vue logic of each element and not using it in parent.

2024-07-05 08:42 UTC, ga-devfront commented on _dev/yarn.lock
I think you don't have to publish the yarn.lock

2024-07-05 13:13 UTC, ClaraLpresta commented on .gitignore
Because all these files are generated as soon as I launch the application.

2024-07-05 13:23 UTC, Quetzacoalt91 commented on .gitignore
I'm fine with this change :+1:

2024-07-09 07:20 UTC, ga-devfront approved these changes

2024-07-09 07:21 UTC, merged