EMKTG-3393 - Field requiered in Attribute Mapping
PrestaShopCorp/psxmarketingwithgoogle pull request #1776
Opened 2024-07-04 15:20 UTC by ClaraLpresta

2024-07-05 07:55 UTC, ga-devfront requested changes

2024-07-05 07:55 UTC, ga-devfront commented on _dev/apps/ui/src/components/product-feed/settings/attribute-mapping/attribute-mapping.vue
> +      if (this.hasError) return;
It's not good. We will test all the values ​​one by one and directly change the hasError however if the last one does not have one the field will be false THEN there may be errors before.
You should rather reset the hasError at the beginning (false) then do a hasError = myMethod || hasError to let the possibility to be true

2024-07-05 13:13 UTC, ga-devfront reviewed
another thing. Why do you use a global variable if you don't use it anywere else ? You can just use a const in this case no ?

2024-07-08 07:40 UTC, ga-devfront approved these changes
the difference is not huge, but when declared in data() the data persists and therefore requires more resources. Except here, we don't need its persistence, because we recalculate its value each time without it impacting the rest.

2024-07-08 07:43 UTC, ClaraLpresta commented
@ga-devfront I understand, good to know! Thanks

2024-07-09 09:28 UTC, merged