Refacto : pagination on campaigns performance's list
PrestaShopCorp/psxmarketingwithgoogle pull request #868
Opened 2022-02-21 18:55 UTC by elisegriset92

2022-02-24 13:29 UTC, tberger-prestashop approved these changes
J'approuve mais je n'y connais pas grand chose en VueJS 😨

2022-02-24 13:34 UTC, PoulainMaxime requested changes

2022-02-24 13:34 UTC, PoulainMaxime commented on _dev/src/components/smart-shopping-campaign/reporting/campaigns-performance/campaigns-performance-table.vue
> +      / this.$store.getters['smartShoppingCampaigns/GET_LIMIT_CAMPAIGN_PERFORMANCE_LIST'];
Careful here, you need to delete '/' because the app cannot be compiled

2022-02-24 13:35 UTC, PoulainMaxime approved these changes

2022-02-28 17:11 UTC, Quetzacoalt91 approved these changes
Ready for merge after the release of v1.15.0

2022-03-01 09:43 UTC, merged