Modify the UI for attribute mapping summary
PrestaShopCorp/psxmarketingwithgoogle pull request #999
Opened 2022-04-22 07:47 UTC by PoulainMaxime

2022-04-22 08:19 UTC, elisegriset92 reviewed
Need linter and maybe review from @amaury-hanser ?

2022-04-22 08:20 UTC, Quetzacoalt91 commented on _dev/src/components/product-feed/commons/table-row-mapping.vue
> +          <i class="material-icons-outlined align-items-with-text" v-if="attributeNotMapped">
Linter reported some issues to take in account

2022-04-22 14:08 UTC, Quetzacoalt91 submitted a review, later dismissed

2022-04-22 14:12 UTC, amaury-hanser requested changes
Som qui changes, moving rule in correct file and use the arrow icon in a `background-image`

2022-04-22 14:12 UTC, amaury-hanser commented on _dev/src/assets/scss/layouts/_table.scss
> +.table-border-bottom {
Is it different from the class `border-bottom` ?

2022-04-22 14:12 UTC, amaury-hanser commented on _dev/src/components/product-feed/settings/summary/summary.vue
> +                        <img
Should be a `background-image` on the `tr`

2022-04-26 13:34 UTC, amaury-hanser approved these changes

2022-04-27 07:52 UTC, merged